In [21]:
import pandas as pd
from io import BytesIO

In [ ]:

file_path = "C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/tcga_brca_counts.csv"
dfcounts = pd.read_csv(file_path, index_col=0)

In [3]:
dfcounts

,TCGA-BH-A18H-01A-11R-A12D-07,TCGA-E2-A14P-01A-31R-A12D-07,TCGA-AN-A04A-01A-21R-A034-07,TCGA-5L-AAT1-01A-12R-A41B-07,TCGA-GI-A2C8-11A-22R-A16F-07,TCGA-AQ-A0Y5-01A-11R-A14M-07,TCGA-A8-A07I-01A-11R-A00Z-07,TCGA-E9-A1R4-01A-21R-A14D-07,TCGA-AC-A8OP-01A-11R-A36F-07,TCGA-AR-A24Q-01A-12R-A169-07,...,TCGA-AR-A255-01A-11R-A169-07,TCGA-B6-A0WX-01A-11R-A109-07,TCGA-EW-A1J2-01A-21R-A13Q-07,TCGA-A1-A0SP-01A-11R-A084-07,TCGA-BH-A1F8-01A-11R-A13Q-07,TCGA-BH-A1F8-11B-21R-A13Q-07,TCGA-AC-A3HN-01A-11R-A213-07,TCGA-B6-A0RT-01A-21R-A084-07,TCGA-A8-A08P-01A-11R-A00Z-07,TCGA-BH-A0HN-01A-11R-A10U-07
ENSG00000000003.15,426,1033,1417,929,420,879,1117,711,786,3750,...,1980,4679,8752,4246,6779,3778,1884,1494,898,648
ENSG00000000005.6,3,21,9,3,16,9,29,15,88,390,...,142,2,74,6,2,131,339,78,4,0
ENSG00000000419.13,1439,4553,1982,933,1664,2623,1426,1943,1494,3856,...,4253,2570,2486,2498,6972,1468,2256,3955,3631,1475
ENSG00000000457.14,1049,932,1227,802,654,1727,974,1285,1052,1416,...,1617,1342,3692,791,1562,830,2420,812,1077,1412
ENSG00000000460.17,326,463,284,143,84,421,467,549,229,1178,...,625,1121,885,917,654,215,818,404,816,299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000288669.1,0,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,2,0,0,0,0
ENSG00000288670.1,297,207,279,149,1720,767,1615,187,208,397,...,873,859,730,361,275,163,525,349,363,340
ENSG00000288671.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000288674.1,6,2,0,1,19,6,3,1,8,4,...,9,14,14,7,2,5,9,8,4,7
ENSG00000288675.1,34,39,32,29,1,37,16,53,21,28,...,12,27,17,29,8,9,41,44,13,39

In [4]:

file_path = "C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/tcga_brca_clinical.csv"
dfclinical = pd.read_csv(file_path, index_col=0)

In [5]:
dfclinical.head()

,barcode,patient,sample,shortLetterCode,definition,sample_submitter_id,tumor_descriptor,sample_id,pathology_report_uuid,submitter_id,...,paper_tobacco_smoking_history,paper_CNV.Clusters,paper_Mutation.Clusters,paper_DNA.Methylation.Clusters,paper_mRNA.Clusters,paper_miRNA.Clusters,paper_lncRNA.Clusters,paper_Protein.Clusters,paper_PARADIGM.Clusters,paper_Pan.Gyn.Clusters
TCGA-BH-A18H-01A-11R-A12D-07,TCGA-BH-A18H-01A-11R-A12D-07,TCGA-BH-A18H,TCGA-BH-A18H-01A,TP,Primary solid Tumor,TCGA-BH-A18H-01A,Primary,9321161b-d568-4d38-aed3-956786a06329,DF536409-601F-489B-9F8A-A2B372BF9999,TCGA-BH-A18H,...,NaN,C4,C4,C1,C2,C3,C1,C1,C6,C3
TCGA-E2-A14P-01A-31R-A12D-07,TCGA-E2-A14P-01A-31R-A12D-07,TCGA-E2-A14P,TCGA-E2-A14P-01A,TP,Primary solid Tumor,TCGA-E2-A14P-01A,Primary,58bfe278-a80f-4722-b286-4d966214d244,FD8CDFD9-6DCF-4CE1-9BB1-A7FF568EE53C,TCGA-E2-A14P,...,NaN,C4,C4,C1,C2,C7,C2,C1,C4,C3
TCGA-AN-A04A-01A-21R-A034-07,TCGA-AN-A04A-01A-21R-A034-07,TCGA-AN-A04A,TCGA-AN-A04A-01A,TP,Primary solid Tumor,TCGA-AN-A04A-01A,Primary,1d8f72b7-8596-40e8-afdf-244dd897758c,6FB7A794-C3E7-4501-A844-CF65B9C3D32C,TCGA-AN-A04A,...,NaN,C6,C1,C1,C1,C3,C2,C1,C5,C5
TCGA-5L-AAT1-01A-12R-A41B-07,TCGA-5L-AAT1-01A-12R-A41B-07,TCGA-5L-AAT1,TCGA-5L-AAT1-01A,TP,Primary solid Tumor,TCGA-5L-AAT1-01A,Primary,a31dec9b-3626-4cb0-8265-1425d5ce1c1e,B5CA42BB-9514-42C6-9FB0-C8889C1DC51A,TCGA-5L-AAT1,...,NaN,NaN,C9,C1,C2,NaN,NaN,C2,NaN,C1
TCGA-GI-A2C8-11A-22R-A16F-07,TCGA-GI-A2C8-11A-22R-A16F-07,TCGA-GI-A2C8,TCGA-GI-A2C8-11A,NT,Solid Tissue Normal,TCGA-GI-A2C8-11A,Not Applicable,2a679581-38ad-4742-8d7b-89015df11e7d,NaN,TCGA-GI-A2C8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
dfclinical.loc[:,'barcode']   #ID Card

TCGA-BH-A18H-01A-11R-A12D-07    TCGA-BH-A18H-01A-11R-A12D-07
TCGA-E2-A14P-01A-31R-A12D-07    TCGA-E2-A14P-01A-31R-A12D-07
TCGA-AN-A04A-01A-21R-A034-07    TCGA-AN-A04A-01A-21R-A034-07
TCGA-5L-AAT1-01A-12R-A41B-07    TCGA-5L-AAT1-01A-12R-A41B-07
TCGA-GI-A2C8-11A-22R-A16F-07    TCGA-GI-A2C8-11A-22R-A16F-07
TCGA-AQ-A0Y5-01A-11R-A14M-07    TCGA-AQ-A0Y5-01A-11R-A14M-07
TCGA-A8-A07I-01A-11R-A00Z-07    TCGA-A8-A07I-01A-11R-A00Z-07
TCGA-E9-A1R4-01A-21R-A14D-07    TCGA-E9-A1R4-01A-21R-A14D-07
TCGA-AC-A8OP-01A-11R-A36F-07    TCGA-AC-A8OP-01A-11R-A36F-07
TCGA-AR-A24Q-01A-12R-A169-07    TCGA-AR-A24Q-01A-12R-A169-07
TCGA-D8-A1XU-01A-11R-A14M-07    TCGA-D8-A1XU-01A-11R-A14M-07
TCGA-AO-A03N-01B-11R-A10J-07    TCGA-AO-A03N-01B-11R-A10J-07
TCGA-A1-A0SN-01A-11R-A144-07    TCGA-A1-A0SN-01A-11R-A144-07
TCGA-D8-A1JP-01A-11R-A13Q-07    TCGA-D8-A1JP-01A-11R-A13Q-07
TCGA-D8-A1XL-01A-11R-A14M-07    TCGA-D8-A1XL-01A-11R-A14M-07
TCGA-B6-A1KI-01A-11R-A14M-07    TCGA-B6-A1KI-01A-11R-A14M-07
TCGA-B6-A0IP-01A-11R-A034-07    TCGA-B6-A0IP-01A-11R-A034-07
TCGA-B6-A0IM-01A-11R-A034-07    TCGA-B6-A0IM-01A-11R-A034-07
TCGA-A1-A0SB-01A-11R-A144-07    TCGA-A1-A0SB-01A-11R-A144-07
TCGA-A8-A08B-01A-11R-A00Z-07    TCGA-A8-A08B-01A-11R-A00Z-07
TCGA-AN-A0FD-01A-11R-A034-07    TCGA-AN-A0FD-01A-11R-A034-07
TCGA-3C-AALJ-01A-31R-A41B-07    TCGA-3C-AALJ-01A-31R-A41B-07
TCGA-AC-A4ZE-01A-11R-A41B-07    TCGA-AC-A4ZE-01A-11R-A41B-07
TCGA-AO-A124-01A-11R-A10J-07    TCGA-AO-A124-01A-11R-A10J-07
TCGA-AR-A24M-01A-11R-A169-07    TCGA-AR-A24M-01A-11R-A169-07
TCGA-E9-A22A-01A-11R-A157-07    TCGA-E9-A22A-01A-11R-A157-07
TCGA-BH-A0BZ-01A-31R-A12P-07    TCGA-BH-A0BZ-01A-31R-A12P-07
TCGA-BH-A0BW-11A-12R-A115-07    TCGA-BH-A0BW-11A-12R-A115-07
TCGA-BH-A1FE-11B-14R-A13Q-07    TCGA-BH-A1FE-11B-14R-A13Q-07
TCGA-A8-A07F-01A-11R-A00Z-07    TCGA-A8-A07F-01A-11R-A00Z-07
TCGA-B6-A0WT-01A-11R-A109-07    TCGA-B6-A0WT-01A-11R-A109-07
TCGA-C8-A12Y-01A-11R-A12D-07    TCGA-C8-A12Y-01A-11R-A12D-07
TCGA-AN-A0FF-01A-11R-A034-07    TCGA-AN-A0FF-01A-11R-A034-07
TCGA-BH-A1F5-01A-12R-A13Q-07    TCGA-BH-A1F5-01A-12R-A13Q-07
TCGA-D8-A1Y2-01A-11R-A157-07    TCGA-D8-A1Y2-01A-11R-A157-07
TCGA-BH-A1FB-11A-33R-A13Q-07    TCGA-BH-A1FB-11A-33R-A13Q-07
TCGA-BH-A0B6-01A-11R-A19W-07    TCGA-BH-A0B6-01A-11R-A19W-07
TCGA-A8-A093-01A-11R-A00Z-07    TCGA-A8-A093-01A-11R-A00Z-07
TCGA-E9-A1NF-11A-73R-A14D-07    TCGA-E9-A1NF-11A-73R-A14D-07
TCGA-E2-A1B1-01A-21R-A12P-07    TCGA-E2-A1B1-01A-21R-A12P-07
TCGA-AR-A255-01A-11R-A169-07    TCGA-AR-A255-01A-11R-A169-07
TCGA-B6-A0WX-01A-11R-A109-07    TCGA-B6-A0WX-01A-11R-A109-07
TCGA-EW-A1J2-01A-21R-A13Q-07    TCGA-EW-A1J2-01A-21R-A13Q-07
TCGA-A1-A0SP-01A-11R-A084-07    TCGA-A1-A0SP-01A-11R-A084-07
TCGA-BH-A1F8-01A-11R-A13Q-07    TCGA-BH-A1F8-01A-11R-A13Q-07
TCGA-BH-A1F8-11B-21R-A13Q-07    TCGA-BH-A1F8-11B-21R-A13Q-07
TCGA-AC-A3HN-01A-11R-A213-07    TCGA-AC-A3HN-01A-11R-A213-07
TCGA-B6-A0RT-01A-21R-A084-07    TCGA-B6-A0RT-01A-21R-A084-07
TCGA-A8-A08P-01A-11R-A00Z-07    TCGA-A8-A08P-01A-11R-A00Z-07
TCGA-BH-A0HN-01A-11R-A10U-07    TCGA-BH-A0HN-01A-11R-A10U-07
Name: barcode, dtype: object

In [7]:
dfclinical.loc[:,'paper_BRCA_Subtype_PAM50']  #molecular subtype

TCGA-BH-A18H-01A-11R-A12D-07      LumA
TCGA-E2-A14P-01A-31R-A12D-07      Her2
TCGA-AN-A04A-01A-21R-A034-07      LumA
TCGA-5L-AAT1-01A-12R-A41B-07      LumA
TCGA-GI-A2C8-11A-22R-A16F-07       NaN
TCGA-AQ-A0Y5-01A-11R-A14M-07      LumA
TCGA-A8-A07I-01A-11R-A00Z-07      Her2
TCGA-E9-A1R4-01A-21R-A14D-07      LumB
TCGA-AC-A8OP-01A-11R-A36F-07      LumA
TCGA-AR-A24Q-01A-12R-A169-07     Basal
TCGA-D8-A1XU-01A-11R-A14M-07      LumA
TCGA-AO-A03N-01B-11R-A10J-07      LumB
TCGA-A1-A0SN-01A-11R-A144-07      LumB
TCGA-D8-A1JP-01A-11R-A13Q-07      LumA
TCGA-D8-A1XL-01A-11R-A14M-07      LumB
TCGA-B6-A1KI-01A-11R-A14M-07      LumA
TCGA-B6-A0IP-01A-11R-A034-07      LumA
TCGA-B6-A0IM-01A-11R-A034-07      LumA
TCGA-A1-A0SB-01A-11R-A144-07    Normal
TCGA-A8-A08B-01A-11R-A00Z-07      Her2
TCGA-AN-A0FD-01A-11R-A034-07      LumA
TCGA-3C-AALJ-01A-31R-A41B-07      LumB
TCGA-AC-A4ZE-01A-11R-A41B-07      LumA
TCGA-AO-A124-01A-11R-A10J-07     Basal
TCGA-AR-A24M-01A-11R-A169-07      LumA
TCGA-E9-A22A-01A-11R-A157-07      LumB
TCGA-BH-A0BZ-01A-31R-A12P-07      LumB
TCGA-BH-A0BW-11A-12R-A115-07       NaN
TCGA-BH-A1FE-11B-14R-A13Q-07       NaN
TCGA-A8-A07F-01A-11R-A00Z-07      LumA
TCGA-B6-A0WT-01A-11R-A109-07      LumA
TCGA-C8-A12Y-01A-11R-A12D-07      LumA
TCGA-AN-A0FF-01A-11R-A034-07      LumB
TCGA-BH-A1F5-01A-12R-A13Q-07      LumA
TCGA-D8-A1Y2-01A-11R-A157-07      LumB
TCGA-BH-A1FB-11A-33R-A13Q-07       NaN
TCGA-BH-A0B6-01A-11R-A19W-07      LumA
TCGA-A8-A093-01A-11R-A00Z-07      LumA
TCGA-E9-A1NF-11A-73R-A14D-07       NaN
TCGA-E2-A1B1-01A-21R-A12P-07      LumA
TCGA-AR-A255-01A-11R-A169-07      LumA
TCGA-B6-A0WX-01A-11R-A109-07     Basal
TCGA-EW-A1J2-01A-21R-A13Q-07      LumA
TCGA-A1-A0SP-01A-11R-A084-07     Basal
TCGA-BH-A1F8-01A-11R-A13Q-07      LumB
TCGA-BH-A1F8-11B-21R-A13Q-07       NaN
TCGA-AC-A3HN-01A-11R-A213-07      LumA
TCGA-B6-A0RT-01A-21R-A084-07     Basal
TCGA-A8-A08P-01A-11R-A00Z-07      LumB
TCGA-BH-A0HN-01A-11R-A10U-07      LumA
Name: paper_BRCA_Subtype_PAM50, dtype: object

In [8]:
dfclinical.loc[:,'ajcc_pathologic_stage']

TCGA-BH-A18H-01A-11R-A12D-07      Stage IA
TCGA-E2-A14P-01A-31R-A12D-07    Stage IIIC
TCGA-AN-A04A-01A-21R-A034-07    Stage IIIA
TCGA-5L-AAT1-01A-12R-A41B-07      Stage IV
TCGA-GI-A2C8-11A-22R-A16F-07    Stage IIIB
TCGA-AQ-A0Y5-01A-11R-A14M-07           NaN
TCGA-A8-A07I-01A-11R-A00Z-07    Stage IIIA
TCGA-E9-A1R4-01A-21R-A14D-07      Stage IA
TCGA-AC-A8OP-01A-11R-A36F-07      Stage IA
TCGA-AR-A24Q-01A-12R-A169-07     Stage IIB
TCGA-D8-A1XU-01A-11R-A14M-07      Stage IA
TCGA-AO-A03N-01B-11R-A10J-07           NaN
TCGA-A1-A0SN-01A-11R-A144-07     Stage IIA
TCGA-D8-A1JP-01A-11R-A13Q-07      Stage IA
TCGA-D8-A1XL-01A-11R-A14M-07     Stage IIB
TCGA-B6-A1KI-01A-11R-A14M-07       Stage I
TCGA-B6-A0IP-01A-11R-A034-07      Stage IA
TCGA-B6-A0IM-01A-11R-A034-07     Stage IIB
TCGA-A1-A0SB-01A-11R-A144-07       Stage I
TCGA-A8-A08B-01A-11R-A00Z-07     Stage IIA
TCGA-AN-A0FD-01A-11R-A034-07     Stage IIA
TCGA-3C-AALJ-01A-31R-A41B-07     Stage IIB
TCGA-AC-A4ZE-01A-11R-A41B-07     Stage IIB
TCGA-AO-A124-01A-11R-A10J-07     Stage IIA
TCGA-AR-A24M-01A-11R-A169-07    Stage IIIA
TCGA-E9-A22A-01A-11R-A157-07     Stage IIA
TCGA-BH-A0BZ-01A-31R-A12P-07    Stage IIIA
TCGA-BH-A0BW-11A-12R-A115-07       Stage I
TCGA-BH-A1FE-11B-14R-A13Q-07     Stage IIB
TCGA-A8-A07F-01A-11R-A00Z-07     Stage IIB
TCGA-B6-A0WT-01A-11R-A109-07           NaN
TCGA-C8-A12Y-01A-11R-A12D-07     Stage IIB
TCGA-AN-A0FF-01A-11R-A034-07      Stage IA
TCGA-BH-A1F5-01A-12R-A13Q-07     Stage IIA
TCGA-D8-A1Y2-01A-11R-A157-07     Stage IIA
TCGA-BH-A1FB-11A-33R-A13Q-07     Stage IIB
TCGA-BH-A0B6-01A-11R-A19W-07       Stage I
TCGA-A8-A093-01A-11R-A00Z-07           NaN
TCGA-E9-A1NF-11A-73R-A14D-07           NaN
TCGA-E2-A1B1-01A-21R-A12P-07     Stage IIB
TCGA-AR-A255-01A-11R-A169-07       Stage I
TCGA-B6-A0WX-01A-11R-A109-07    Stage IIIA
TCGA-EW-A1J2-01A-21R-A13Q-07           NaN
TCGA-A1-A0SP-01A-11R-A084-07           NaN
TCGA-BH-A1F8-01A-11R-A13Q-07    Stage IIIB
TCGA-BH-A1F8-11B-21R-A13Q-07    Stage IIIB
TCGA-AC-A3HN-01A-11R-A213-07     Stage IIB
TCGA-B6-A0RT-01A-21R-A084-07    Stage IIIA
TCGA-A8-A08P-01A-11R-A00Z-07    Stage IIIA
TCGA-BH-A0HN-01A-11R-A10U-07      Stage IA
Name: ajcc_pathologic_stage, dtype: object

In [9]:
dfclinical.loc[:,'age_at_diagnosis']

TCGA-BH-A18H-01A-11R-A12D-07    23065.0
TCGA-E2-A14P-01A-31R-A12D-07    28923.0
TCGA-AN-A04A-01A-21R-A034-07    13445.0
TCGA-5L-AAT1-01A-12R-A41B-07    23225.0
TCGA-GI-A2C8-11A-22R-A16F-07    23103.0
TCGA-AQ-A0Y5-01A-11R-A14M-07        NaN
TCGA-A8-A07I-01A-11R-A00Z-07    25263.0
TCGA-E9-A1R4-01A-21R-A14D-07    24181.0
TCGA-AC-A8OP-01A-11R-A36F-07    26550.0
TCGA-AR-A24Q-01A-12R-A169-07    18084.0
TCGA-D8-A1XU-01A-11R-A14M-07    20715.0
TCGA-AO-A03N-01B-11R-A10J-07    23461.0
TCGA-A1-A0SN-01A-11R-A144-07    18401.0
TCGA-D8-A1JP-01A-11R-A13Q-07    26862.0
TCGA-D8-A1XL-01A-11R-A14M-07    12668.0
TCGA-B6-A1KI-01A-11R-A14M-07    23031.0
TCGA-B6-A0IP-01A-11R-A034-07    27047.0
TCGA-B6-A0IM-01A-11R-A034-07    27557.0
TCGA-A1-A0SB-01A-11R-A144-07    25833.0
TCGA-A8-A08B-01A-11R-A00Z-07    19114.0
TCGA-AN-A0FD-01A-11R-A034-07    26007.0
TCGA-3C-AALJ-01A-31R-A41B-07    22848.0
TCGA-AC-A4ZE-01A-11R-A41B-07    23284.0
TCGA-AO-A124-01A-11R-A10J-07    14174.0
TCGA-AR-A24M-01A-11R-A169-07    14119.0
TCGA-E9-A22A-01A-11R-A157-07    27288.0
TCGA-BH-A0BZ-01A-31R-A12P-07    21856.0
TCGA-BH-A0BW-11A-12R-A115-07    25974.0
TCGA-BH-A1FE-11B-14R-A13Q-07    11650.0
TCGA-A8-A07F-01A-11R-A00Z-07    23742.0
TCGA-B6-A0WT-01A-11R-A109-07    26224.0
TCGA-C8-A12Y-01A-11R-A12D-07        NaN
TCGA-AN-A0FF-01A-11R-A034-07    11929.0
TCGA-BH-A1F5-01A-12R-A13Q-07    22842.0
TCGA-D8-A1Y2-01A-11R-A157-07    26021.0
TCGA-BH-A1FB-11A-33R-A13Q-07    21933.0
TCGA-BH-A0B6-01A-11R-A19W-07        NaN
TCGA-A8-A093-01A-11R-A00Z-07        NaN
TCGA-E9-A1NF-11A-73R-A14D-07    22071.0
TCGA-E2-A1B1-01A-21R-A12P-07    16603.0
TCGA-AR-A255-01A-11R-A169-07    22809.0
TCGA-B6-A0WX-01A-11R-A109-07    14784.0
TCGA-EW-A1J2-01A-21R-A13Q-07    18558.0
TCGA-A1-A0SP-01A-11R-A084-07        NaN
TCGA-BH-A1F8-01A-11R-A13Q-07    32871.0
TCGA-BH-A1F8-11B-21R-A13Q-07    32871.0
TCGA-AC-A3HN-01A-11R-A213-07    32061.0
TCGA-B6-A0RT-01A-21R-A084-07    14374.0
TCGA-A8-A08P-01A-11R-A00Z-07    25598.0
TCGA-BH-A0HN-01A-11R-A10U-07    24731.0
Name: age_at_diagnosis, dtype: float64

In [10]:
dfclinical.loc[:,'gender']

TCGA-BH-A18H-01A-11R-A12D-07    female
TCGA-E2-A14P-01A-31R-A12D-07    female
TCGA-AN-A04A-01A-21R-A034-07    female
TCGA-5L-AAT1-01A-12R-A41B-07    female
TCGA-GI-A2C8-11A-22R-A16F-07    female
TCGA-AQ-A0Y5-01A-11R-A14M-07    female
TCGA-A8-A07I-01A-11R-A00Z-07    female
TCGA-E9-A1R4-01A-21R-A14D-07    female
TCGA-AC-A8OP-01A-11R-A36F-07    female
TCGA-AR-A24Q-01A-12R-A169-07    female
TCGA-D8-A1XU-01A-11R-A14M-07    female
TCGA-AO-A03N-01B-11R-A10J-07    female
TCGA-A1-A0SN-01A-11R-A144-07    female
TCGA-D8-A1JP-01A-11R-A13Q-07    female
TCGA-D8-A1XL-01A-11R-A14M-07    female
TCGA-B6-A1KI-01A-11R-A14M-07    female
TCGA-B6-A0IP-01A-11R-A034-07    female
TCGA-B6-A0IM-01A-11R-A034-07    female
TCGA-A1-A0SB-01A-11R-A144-07    female
TCGA-A8-A08B-01A-11R-A00Z-07    female
TCGA-AN-A0FD-01A-11R-A034-07    female
TCGA-3C-AALJ-01A-31R-A41B-07    female
TCGA-AC-A4ZE-01A-11R-A41B-07    female
TCGA-AO-A124-01A-11R-A10J-07    female
TCGA-AR-A24M-01A-11R-A169-07    female
TCGA-E9-A22A-01A-11R-A157-07    female
TCGA-BH-A0BZ-01A-31R-A12P-07    female
TCGA-BH-A0BW-11A-12R-A115-07    female
TCGA-BH-A1FE-11B-14R-A13Q-07    female
TCGA-A8-A07F-01A-11R-A00Z-07    female
TCGA-B6-A0WT-01A-11R-A109-07    female
TCGA-C8-A12Y-01A-11R-A12D-07    female
TCGA-AN-A0FF-01A-11R-A034-07    female
TCGA-BH-A1F5-01A-12R-A13Q-07    female
TCGA-D8-A1Y2-01A-11R-A157-07    female
TCGA-BH-A1FB-11A-33R-A13Q-07    female
TCGA-BH-A0B6-01A-11R-A19W-07    female
TCGA-A8-A093-01A-11R-A00Z-07    female
TCGA-E9-A1NF-11A-73R-A14D-07    female
TCGA-E2-A1B1-01A-21R-A12P-07    female
TCGA-AR-A255-01A-11R-A169-07    female
TCGA-B6-A0WX-01A-11R-A109-07    female
TCGA-EW-A1J2-01A-21R-A13Q-07    female
TCGA-A1-A0SP-01A-11R-A084-07    female
TCGA-BH-A1F8-01A-11R-A13Q-07    female
TCGA-BH-A1F8-11B-21R-A13Q-07    female
TCGA-AC-A3HN-01A-11R-A213-07    female
TCGA-B6-A0RT-01A-21R-A084-07    female
TCGA-A8-A08P-01A-11R-A00Z-07    female
TCGA-BH-A0HN-01A-11R-A10U-07    female
Name: gender, dtype: object

In [11]:
dfclinical.loc[:,'vital_status']

TCGA-BH-A18H-01A-11R-A12D-07    Alive
TCGA-E2-A14P-01A-31R-A12D-07    Alive
TCGA-AN-A04A-01A-21R-A034-07    Alive
TCGA-5L-AAT1-01A-12R-A41B-07    Alive
TCGA-GI-A2C8-11A-22R-A16F-07    Alive
TCGA-AQ-A0Y5-01A-11R-A14M-07     Dead
TCGA-A8-A07I-01A-11R-A00Z-07    Alive
TCGA-E9-A1R4-01A-21R-A14D-07    Alive
TCGA-AC-A8OP-01A-11R-A36F-07    Alive
TCGA-AR-A24Q-01A-12R-A169-07    Alive
TCGA-D8-A1XU-01A-11R-A14M-07    Alive
TCGA-AO-A03N-01B-11R-A10J-07    Alive
TCGA-A1-A0SN-01A-11R-A144-07    Alive
TCGA-D8-A1JP-01A-11R-A13Q-07    Alive
TCGA-D8-A1XL-01A-11R-A14M-07    Alive
TCGA-B6-A1KI-01A-11R-A14M-07    Alive
TCGA-B6-A0IP-01A-11R-A034-07     Dead
TCGA-B6-A0IM-01A-11R-A034-07     Dead
TCGA-A1-A0SB-01A-11R-A144-07    Alive
TCGA-A8-A08B-01A-11R-A00Z-07    Alive
TCGA-AN-A0FD-01A-11R-A034-07    Alive
TCGA-3C-AALJ-01A-31R-A41B-07    Alive
TCGA-AC-A4ZE-01A-11R-A41B-07    Alive
TCGA-AO-A124-01A-11R-A10J-07    Alive
TCGA-AR-A24M-01A-11R-A169-07    Alive
TCGA-E9-A22A-01A-11R-A157-07    Alive
TCGA-BH-A0BZ-01A-31R-A12P-07    Alive
TCGA-BH-A0BW-11A-12R-A115-07    Alive
TCGA-BH-A1FE-11B-14R-A13Q-07     Dead
TCGA-A8-A07F-01A-11R-A00Z-07    Alive
TCGA-B6-A0WT-01A-11R-A109-07    Alive
TCGA-C8-A12Y-01A-11R-A12D-07    Alive
TCGA-AN-A0FF-01A-11R-A034-07    Alive
TCGA-BH-A1F5-01A-12R-A13Q-07     Dead
TCGA-D8-A1Y2-01A-11R-A157-07    Alive
TCGA-BH-A1FB-11A-33R-A13Q-07     Dead
TCGA-BH-A0B6-01A-11R-A19W-07    Alive
TCGA-A8-A093-01A-11R-A00Z-07    Alive
TCGA-E9-A1NF-11A-73R-A14D-07     Dead
TCGA-E2-A1B1-01A-21R-A12P-07    Alive
TCGA-AR-A255-01A-11R-A169-07    Alive
TCGA-B6-A0WX-01A-11R-A109-07     Dead
TCGA-EW-A1J2-01A-21R-A13Q-07    Alive
TCGA-A1-A0SP-01A-11R-A084-07    Alive
TCGA-BH-A1F8-01A-11R-A13Q-07     Dead
TCGA-BH-A1F8-11B-21R-A13Q-07     Dead
TCGA-AC-A3HN-01A-11R-A213-07    Alive
TCGA-B6-A0RT-01A-21R-A084-07    Alive
TCGA-A8-A08P-01A-11R-A00Z-07    Alive
TCGA-BH-A0HN-01A-11R-A10U-07    Alive
Name: vital_status, dtype: object

In [12]:

dfmodel=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/model_list.csv")

In [13]:
dfmodel

,model_id,sample_id,patient_id,parent_id,model_name,synonyms,tissue,cancer_type,cancer_type_ncit_id,tissue_status,...,pms2_expression_by_ihc,msh6_expression_by_ihc,braf_mutation_identified,braf_expression_by_ihc,pik3ca_mutation_identified,pten_expression_by_ihc,pten_mutation_identified,kras_mutation_identified,mismatch_repair_status,preoperative_ce_alevel
0,SIDM01774,SIDS01659,SIDP01578,NaN,PK-59,NaN,Pancreas,Pancreatic Carcinoma,C3850,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SIDM00192,SIDS00612,SIDP00541,NaN,SNU-1033,NaN,Large Intestine,Colorectal Carcinoma,C9383,Tumour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SIDM01447,SIDS01466,SIDP01347,NaN,SNU-466,NaN,Central Nervous System,Glioblastoma,C3058,Tumour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SIDM01554,SIDS01363,SIDP01247,NaN,IST-MES-2,NaN,Lung,Mesothelioma,C45662,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SIDM01689,SIDS01631,SIDP01557,NaN,MUTZ-5,NaN,Haematopoietic and Lymphoid,B-Lymphoblastic Leukemia,C8644,Tumour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261,SIDM02240,SIDS02049,SIDP01944,NaN,WTSI-COLIVM_041,NaN,Large Intestine,Colorectal Carcinoma,C4349,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2262,SIDM02234,SIDS02055,SIDP01950,NaN,WTSI-COLIVM_057,NaN,Large Intestine,Colorectal Carcinoma,C4349,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2263,SIDM02266,SIDS02075,SIDP01969,NaN,WTSI-COLIVM_093,NaN,Large Intestine,Colorectal Carcinoma,C4349,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2264,SIDM02051,SIDS01956,SIDP01852,NaN,WTSI-COLO_378,HCM-SANG-1311-C18,Large Intestine,Colorectal Carcinoma,C4349,Tumour,...,Positive,Positive,Yes,NaN,NaN,NaN,NaN,No,NaN,NaN
2265,SIDM02074,SIDS01935,SIDP01831,NaN,WTSI-OESO_268,HCM-SANG-1326-C15,Esophagus,Esophageal Carcinoma,C4025,Tumour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
dfmodel.columns

Index(['model_id', 'sample_id', 'patient_id', 'parent_id', 'model_name',
       'synonyms', 'tissue', 'cancer_type', 'cancer_type_ncit_id',
       'tissue_status', 'sample_site', 'cancer_type_detail', 'model_type',
       'growth_properties', 'model_treatment', 'sampling_day',
       'sampling_month', 'sampling_year', 'doi', 'pmed', 'msi_status',
       'ploidy_snp6', 'ploidy_wes', 'ploidy_wgs', 'mutational_burden',
       'model_comments', 'model_relations_comment', 'COSMIC_ID', 'BROAD_ID',
       'CCLE_ID', 'RRID', 'HCMI', 'suppliers', 'supplier', 'cat_number',
       'species', 'gender', 'ethnicity', 'age_at_sampling', 'cris_prediction',
       'cms_prediction', 'family_history_of_cancer', 'prior_same_malignancy',
       'prior_other_malignancy', 'smoking_status',
       'alcohol_exposure_intensity', 'alcohol_consumption_per_week',
       'history_diabetes', 'diabetes_treatment',
       'colorectal_cancer_risk_factors',
       'patient_history_of_gastrointestinal_disorder',
       'gastrointestinal_disorder_diagnosed',
       'prior_synchronous_colon_rectal_tumours', 'history_prior_colon_polyps',
       'previous_current_barretts_oesophagus', 'reflux_disease_prior',
       'reflux_disease_treatment', 'h_pylori_infection',
       'history_clinical_chronic_pancreatitis', 'tumour_grade',
       'tnm_integrated', 'tnm_t', 'tnm_n', 'tnm_m', 'clinical_staging',
       'metastasis_at_diagnosis', 'metastatic_site_at_diagnosis',
       'method_procurement', 'sample_treatment', 'sample_treatment_details',
       'radiation_type', 'prior_therapy_outcome', 'tumour_regression_score',
       'colon_polyps_present_at_time_of_tissue_collection',
       'venous_invasion_present', 'venous_invasion_type',
       'lymphatic_invasion_present', 'perineural_invasion_present',
       'gastric_oesophageal_junction', 'barretts_goblet_cells_present',
       'oesophageal_columnar_metaplasia',
       'goblet_cells_oesophageal_columnar_mucosa',
       'degree_of_dysplasia_non_cancerous_oesophageal_columnar_mucosa',
       'peripancreatic_lymph_nodes_tested_surgery',
       'number_positive_peripancreatic_lymph_nodes', 'mlh1_expression_by_ihc',
       'mlh1_promoter_methylation_status', 'msh2_expression_by_ihc',
       'pms2_expression_by_ihc', 'msh6_expression_by_ihc',
       'braf_mutation_identified', 'braf_expression_by_ihc',
       'pik3ca_mutation_identified', 'pten_expression_by_ihc',
       'pten_mutation_identified', 'kras_mutation_identified',
       'mismatch_repair_status', 'preoperative_ce_alevel'],
      dtype='object')

In [15]:
breast = dfmodel[dfmodel['tissue'].str.contains('Breast')]

In [16]:
breast

,model_id,sample_id,patient_id,parent_id,model_name,synonyms,tissue,cancer_type,cancer_type_ncit_id,tissue_status,...,pms2_expression_by_ihc,msh6_expression_by_ihc,braf_mutation_identified,braf_expression_by_ihc,pik3ca_mutation_identified,pten_expression_by_ihc,pten_mutation_identified,kras_mutation_identified,mismatch_repair_status,preoperative_ce_alevel
32,SIDM01037,SIDS00537,SIDP00472,NaN,JIMT-1,NaN,Breast,Breast Carcinoma,C4872,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,SIDM00866,SIDS00129,SIDP00105,NaN,HCC1143,NaN,Breast,Breast Carcinoma,C4017,Tumour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,SIDM00314,SIDS01089,SIDP00978,NaN,ZR-75-1,NaN,Breast,Breast Carcinoma,C4194,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,SIDM01592,SIDS01345,SIDP01230,NaN,Hs-274-T,NaN,Breast,Breast Carcinoma,C4872,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,SIDM00135,SIDS00822,SIDP00735,NaN,Hs-578-T,HS0578T,Breast,Breast Carcinoma,C4194,Tumour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,SIDM01261,SIDS01089,SIDP00978,SIDM00314,YMB-1-E,NaN,Breast,Breast Carcinoma,C4194,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1795,SIDM00148,SIDS00828,SIDP00740,NaN,MCF7,ssMCF-7;MCF7/WT;IBMF-7;MCF7-CTRL,Breast,Breast Carcinoma,C4194,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1802,SIDM00633,SIDS00194,SIDP00157,NaN,MDA-MB-175-VII,MDA-175,Breast,Breast Carcinoma,C4194,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002,SIDM00938,SIDS00469,SIDP00406,NaN,CAL-148,NaN,Breast,Breast Carcinoma,C4872,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004,SIDM01002,SIDS00502,SIDP00439,NaN,EFM-192A,NaN,Breast,Breast Carcinoma,C4872,Metastasis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
print(breast['cancer_type'].unique())

['Breast Carcinoma' 'Non-Cancerous']

In [18]:
df=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/processed/breast_carcinoma_list.csv")

In [19]:
df

     model_id      model_name  tissue       cancer_type  sample_id
0   SIDM01037          JIMT-1  Breast  Breast Carcinoma  SIDS00537
1   SIDM00866         HCC1143  Breast  Breast Carcinoma  SIDS00129
2   SIDM00314         ZR-75-1  Breast  Breast Carcinoma  SIDS01089
3   SIDM01592        Hs-274-T  Breast  Breast Carcinoma  SIDS01345
4   SIDM00135        Hs-578-T  Breast  Breast Carcinoma  SIDS00822
..        ...             ...     ...               ...        ...
75  SIDM01261         YMB-1-E  Breast  Breast Carcinoma  SIDS01089
76  SIDM00148            MCF7  Breast  Breast Carcinoma  SIDS00828
77  SIDM00633  MDA-MB-175-VII  Breast  Breast Carcinoma  SIDS00194
78  SIDM00938         CAL-148  Breast  Breast Carcinoma  SIDS00469
79  SIDM01002        EFM-192A  Breast  Breast Carcinoma  SIDS00502

[80 rows x 5 columns]

In [20]:
df.head()

    model_id model_name  tissue       cancer_type  sample_id
0  SIDM01037     JIMT-1  Breast  Breast Carcinoma  SIDS00537
1  SIDM00866    HCC1143  Breast  Breast Carcinoma  SIDS00129
2  SIDM00314    ZR-75-1  Breast  Breast Carcinoma  SIDS01089
3  SIDM01592   Hs-274-T  Breast  Breast Carcinoma  SIDS01345
4  SIDM00135   Hs-578-T  Breast  Breast Carcinoma  SIDS00822

In [21]:
rna_tpm=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/rnaseq_merged_rsem_tpm_20260323.csv")

C:\Users\abrup\AppData\Local\Temp\ipykernel_3388\3834796054.py:1: DtypeWarning: Columns (3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900) have mixed types. Specify dtype option on import or set low_memory=False.
  rna_tpm=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/rnaseq_merged_rsem_tpm_20260323.csv")

In [22]:
rna_tpm

,model_id,Unnamed: 1,Unnamed: 2,SIDM00001,SIDM00002,SIDM00003,SIDM00005,SIDM00006,SIDM00007,SIDM00008,...,SIDM02262,SIDM02263,SIDM02264,SIDM02265,SIDM02266,SIDM02267,SIDM02268,SIDM02269,SIDM02270,SIDM02271
0,model_name,NaN,NaN,MEC-1,NBsusSR,M14,MDA-MB-134-VI,MCC26,MCC13,MCAS,...,WTSI-COLO_427,WTSI-COLO_425,WTSI-COLO_061,WTSI-COLIVM_100,WTSI-COLIVM_093,WTSI-COLIVM_092,WTSI-COLO_452,WTSI-PANC_131,WTSI-COLIVM_068,WTSI-GAST_200
1,data_source,NaN,NaN,Broad,Sanger,Sanger,Broad,Sanger,Sanger,Broad,...,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger
2,gene_symbol,ensembl_gene_id,gene_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A1BG,ENSG00000121410,SIDG00001,3.853,4.5059,3.9736,5.7038,3.9069,6.1198,0.0566,...,0.1635,0.848,0.2869,0.189,0.5361,3.5583,2.9635,0,0.0976,0
4,A1BG-AS1,ENSG00000268895,SIDG00002,1.8156,2.3868,3.1408,3.3334,2.5801,3.5336,0.0976,...,0,0,0.189,0.0976,0.2141,0.4957,0.3334,0.8953,0.2869,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41143,ZYG11B,ENSG00000162378,SIDG42471,1.926,3.7388,3.7148,2.4463,3.6334,2.9241,2.121,...,1.251,1.433,2.4303,1.6276,2.6485,1.0286,2.3448,1.111,3.2854,2.0426
41144,ZYX,ENSG00000159840,SIDG42472,4.1562,5.2687,6.959,4.0009,8.5417,7.5178,6.3811,...,3.5398,3.9011,6.4499,6.5396,7.2235,4.1587,4.8802,3.4101,6.7605,5.8689
41145,ZYXP1,ENSG00000274572,SIDG42473,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41146,ZZEF1,ENSG00000074755,SIDG42474,3.0959,4.3519,4.3561,3.3813,3.5211,3.5874,2.4725,...,0.5059,1.2265,1.8156,1.8237,2.6508,1.4542,0.9928,0.9561,2.8237,2.7949
41147,ZZZ3,ENSG00000036549,SIDG42475,3.6792,5.4182,5.5622,4.2434,5.1839,4.9435,4.0721,...,2.9819,2.5361,3.696,3.1408,3.1408,2.3045,3.5801,2.4725,4.4269,3.6496

In [23]:
print("Columns available in your TPM file:")
print(rna_tpm.columns.tolist()[:10])

Columns available in your TPM file:
['model_id', 'Unnamed: 1', 'Unnamed: 2', 'SIDM00001', 'SIDM00002', 'SIDM00003', 'SIDM00005', 'SIDM00006', 'SIDM00007', 'SIDM00008']

In [25]:
print(rna_tpm.head())

      model_id       Unnamed: 1 Unnamed: 2 SIDM00001 SIDM00002 SIDM00003  \
0   model_name              NaN        NaN     MEC-1   NBsusSR       M14
1  data_source              NaN        NaN     Broad    Sanger    Sanger
2  gene_symbol  ensembl_gene_id    gene_id       NaN       NaN       NaN
3         A1BG  ENSG00000121410  SIDG00001     3.853    4.5059    3.9736
4     A1BG-AS1  ENSG00000268895  SIDG00002    1.8156    2.3868    3.1408

       SIDM00005 SIDM00006 SIDM00007 SIDM00008  ...      SIDM02262  \
0  MDA-MB-134-VI     MCC26     MCC13      MCAS  ...  WTSI-COLO_427
1          Broad    Sanger    Sanger     Broad  ...         Sanger
2            NaN       NaN       NaN       NaN  ...            NaN
3         5.7038    3.9069    6.1198    0.0566  ...         0.1635
4         3.3334    2.5801    3.5336    0.0976  ...              0

       SIDM02263      SIDM02264        SIDM02265        SIDM02266  \
0  WTSI-COLO_425  WTSI-COLO_061  WTSI-COLIVM_100  WTSI-COLIVM_093
1         Sanger         Sanger           Sanger           Sanger
2            NaN            NaN              NaN              NaN
3          0.848         0.2869            0.189           0.5361
4              0          0.189           0.0976           0.2141

         SIDM02267      SIDM02268      SIDM02269        SIDM02270  \
0  WTSI-COLIVM_092  WTSI-COLO_452  WTSI-PANC_131  WTSI-COLIVM_068
1           Sanger         Sanger         Sanger           Sanger
2              NaN            NaN            NaN              NaN
3           3.5583         2.9635              0           0.0976
4           0.4957         0.3334         0.8953           0.2869

       SIDM02271
0  WTSI-GAST_200
1         Sanger
2            NaN
3              0
4              0

[5 rows x 1901 columns]

In [28]:
gdsc = pd.read_excel("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/GDSC2_fitted_dose_response_27Oct23.xlsx")

In [29]:
gdsc

,DATASET,NLME_RESULT_ID,NLME_CURVE_ID,CELL_LINE_NAME,SANGER_MODEL_ID,CANCER_TYPE,DRUG_ID,DRUG_NAME,PUTATIVE_TARGET,PATHWAY_NAME,MIN_CONC,MAX_CONC,LN_IC50,AUC,RMSE,Z_SCORE
0,GDSC2,343,15946310,PFSK-1,SIDM01132,Other Solid Cancers,1003,Camptothecin,TOP1,DNA replication,0.000100,0.1,-1.463887,0.930220,0.089052,0.433123
1,GDSC2,343,15946548,A673,SIDM00848,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.000100,0.1,-4.869455,0.614970,0.111351,-1.421100
2,GDSC2,343,15946830,ES5,SIDM00263,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.000100,0.1,-3.360586,0.791072,0.142855,-0.599569
3,GDSC2,343,15947087,ES7,SIDM00269,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.000100,0.1,-5.044940,0.592660,0.135539,-1.516647
4,GDSC2,343,15947369,EW-11,SIDM00203,Ewing's Sarcoma,1003,Camptothecin,TOP1,DNA replication,0.000100,0.1,-3.741991,0.734047,0.128059,-0.807232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242031,GDSC2,343,16188242,SNU-175,SIDM00216,Colorectal Carcinoma,2499,N-acetyl cysteine,Metabolism,Metabolism,2.001054,2000.0,10.127082,0.976746,0.074498,0.156872
242032,GDSC2,343,16188695,SNU-407,SIDM00214,Colorectal Carcinoma,2499,N-acetyl cysteine,Metabolism,Metabolism,2.001054,2000.0,8.576377,0.913378,0.057821,-1.626959
242033,GDSC2,343,16188953,SNU-61,SIDM00194,Colorectal Carcinoma,2499,N-acetyl cysteine,Metabolism,Metabolism,2.001054,2000.0,10.519636,0.975001,0.058090,0.608442
242034,GDSC2,343,16189493,SNU-C5,SIDM00498,Colorectal Carcinoma,2499,N-acetyl cysteine,Metabolism,Metabolism,2.001054,2000.0,10.694579,0.969969,0.101013,0.809684
242035,GDSC2,343,16189775,DiFi,SIDM00049,Colorectal Carcinoma,2499,N-acetyl cysteine,Metabolism,Metabolism,2.001054,2000.0,10.034825,0.966988,0.089057,0.050746

In [30]:
id=gdsc["SANGER_MODEL_ID"]

In [31]:
id

0         SIDM01132
1         SIDM00848
2         SIDM00263
3         SIDM00269
4         SIDM00203
            ...
242031    SIDM00216
242032    SIDM00214
242033    SIDM00194
242034    SIDM00498
242035    SIDM00049
Name: SANGER_MODEL_ID, Length: 242036, dtype: object

In [33]:
compounds = pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/screened_compounds_rel_8.5.csv")

In [34]:
compounds

,DRUG_ID,SCREENING_SITE,DRUG_NAME,SYNONYMS,TARGET,TARGET_PATHWAY
0,1,MGH,Erlotinib,"Tarceva, RG-1415, CP-358774, OSI-774, Ro-50823...",EGFR,EGFR signaling
1,3,MGH,Rapamycin,"AY-22989, Sirolimus, WY-090217, Torisel, Rapamune",MTORC1,PI3K/MTOR signaling
2,5,MGH,Sunitinib,"Sutent, Sunitinib Malate, SU-11248","PDGFR, KIT, VEGFR, FLT3, RET, CSF1R",RTK signaling
3,6,MGH,PHA-665752,"PHA665752, PHA 665752",MET,RTK signaling
4,9,MGH,MG-132,"LLL cpd, MG 132, MG132","Proteasome, CAPN1",Protein stability and degradation
...,...,...,...,...,...,...
616,2362,SANGER,THR-103,WIMM synthesis,Mutant RAS,PI3K/MTOR signaling
617,2438,SANGER,ascorbate (vitamin C),back-up solution from YWKim,anti-oxidant proteins,Other
618,2439,SANGER,glutathione,"G6013, sigma",anti-oxidant proteins,Other
619,2498,SANGER,alpha-lipoic acid,aLA,Metabolism,Metabolism
620,2499,SANGER,N-acetyl cysteine,NAC,Metabolism,Metabolism

In [35]:
clean_gdsc=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/processed/clean_gdsc.csv")

In [37]:
enriched_tests = pd.merge(clean_gdsc, compounds[['DRUG_ID', 'DRUG_NAME']], on='DRUG_ID', how='left')

In [38]:
enriched_tests

      SANGER_MODEL_ID  DRUG_ID    LN_IC50          DRUG_NAME
0           SIDM00872     1003   0.317741       Camptothecin
1           SIDM00866     1003   0.636184       Camptothecin
2           SIDM00885     1003   1.235544       Camptothecin
3           SIDM00884     1003  -2.255899       Camptothecin
4           SIDM00877     1003  -3.247021       Camptothecin
...               ...      ...        ...                ...
13383       SIDM01002     2499  11.217375  N-acetyl cysteine
13384       SIDM00881     2499   9.653037  N-acetyl cysteine
13385       SIDM01062     2499  10.939549  N-acetyl cysteine
13386       SIDM01037     2499   9.100781  N-acetyl cysteine
13387       SIDM00879     2499  10.235080  N-acetyl cysteine

[13388 rows x 4 columns]

In [40]:
print(enriched_tests['DRUG_NAME'].isnull().sum())

0

In [41]:
# Save the master table
enriched_tests.to_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/processed/drug_response_enriched.csv", index=False)

In [48]:
drug_smile=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/processed/drug_smiles_map.csv")

In [49]:
drug_smile

,DRUG_ID,DRUG_NAME,SMILES
0,1003,Camptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...
1,1004,Vinblastine,CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(...
2,1005,Cisplatin,N.N.Cl[Pt]Cl
3,1006,Cytarabine,C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O
4,1007,Docetaxel,CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...
...,...,...,...
290,2362,THR-103,NaN
291,2438,ascorbate (vitamin C),NaN
292,2439,glutathione,C(CC(=O)NC(CS)C(=O)NCC(=O)O)C(C(=O)O)N
293,2498,alpha-lipoic acid,C1CSSC1CCCCC(=O)O
294,2499,N-acetyl cysteine,CC(=O)NC(CS)C(=O)O

In [54]:
drug_smile.head()

   DRUG_ID     DRUG_NAME                                             SMILES
0     1003  Camptothecin  CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...
1     1004   Vinblastine  CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(...
2     1005     Cisplatin                                       N.N.Cl[Pt]Cl
3     1006    Cytarabine                 C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O
4     1007     Docetaxel  CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...

In [56]:
drug_smile.isnull().count()

DRUG_ID      295
DRUG_NAME    295
SMILES       295
dtype: int64

In [53]:
drug_smile.loc[drug_smile['SMILES'].isnull(),'DRUG_NAME']

5                  Methotrexate
36                Nutlin-3a (-)
93            Bleomycin (50 uM)
95                     IAP_5620
121                BDOCA000347a
122                BDF00022089a
123                BDILV000379a
144             Picolinici-acid
146                   CDK9_5576
147                   CDK9_5038
148                    Eg5_9814
149                    ERK_2440
150                    ERK_6604
151                  IRAK4_4710
152                   JAK1_8709
154                    PAK_5339
155                   TAF1_5496
156                   ULK1_4989
157                  VSP34_8731
159                  IGF1R_3801
160                    JAK_8517
161                 GSK2256098C
162                 GSK2276186C
164                 GSK626616AC
165                 GSK3337463A
166                 GSK2830371A
167                     LMB_AB1
168                     LMB_AB2
169                     LMB_AB3
187                      123829
188                      765771
189                      123138
191                       50869
193                      720427
194                      667880
197                      729189
198                      741909
199                      743380
201                      150412
203                      615590
204                      630600
206                      776928
213    KRAS (G12C) Inhibitor-12
215                BDP-00009066
244                BPD-00008900
245                N25720-51-A1
246                 N27922-53-1
247                 N30652-18-1
248                 N29087-69-1
269                       VTP-A
270                       VTP-B
271                     PBD-288
273                    CT7033-2
274              GSK-LSD1-2HCl
288                     THR-101
289                     THR-102
290                     THR-103
291       ascorbate (vitamin C)
Name: DRUG_NAME, dtype: object

In [57]:
df=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/processed/final_training_set.csv")

In [68]:
df.describe()

            DRUG_ID       LN_IC50
count  11720.000000  11720.000000
mean    1559.872440      2.920899
std      405.690001      2.767799
min     1003.000000     -7.568085
25%     1088.000000      1.661126
50%     1614.000000      3.393857
75%     1912.000000      4.807312
max     2499.000000     12.265135

In [71]:
gene_check=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/raw/rnaseq_merged_rsem_tpm_20260323.csv",nrows=5)

In [72]:
gene_check

,model_id,Unnamed: 1,Unnamed: 2,SIDM00001,SIDM00002,SIDM00003,SIDM00005,SIDM00006,SIDM00007,SIDM00008,...,SIDM02262,SIDM02263,SIDM02264,SIDM02265,SIDM02266,SIDM02267,SIDM02268,SIDM02269,SIDM02270,SIDM02271
0,model_name,NaN,NaN,MEC-1,NBsusSR,M14,MDA-MB-134-VI,MCC26,MCC13,MCAS,...,WTSI-COLO_427,WTSI-COLO_425,WTSI-COLO_061,WTSI-COLIVM_100,WTSI-COLIVM_093,WTSI-COLIVM_092,WTSI-COLO_452,WTSI-PANC_131,WTSI-COLIVM_068,WTSI-GAST_200
1,data_source,NaN,NaN,Broad,Sanger,Sanger,Broad,Sanger,Sanger,Broad,...,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger,Sanger
2,gene_symbol,ensembl_gene_id,gene_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A1BG,ENSG00000121410,SIDG00001,3.853,4.5059,3.9736,5.7038,3.9069,6.1198,0.0566,...,0.1635,0.848,0.2869,0.189,0.5361,3.5583,2.9635,0,0.0976,0
4,A1BG-AS1,ENSG00000268895,SIDG00002,1.8156,2.3868,3.1408,3.3334,2.5801,3.5336,0.0976,...,0,0,0.189,0.0976,0.2141,0.4957,0.3334,0.8953,0.2869,0

In [73]:
print("Gene File Columns (should be SIDM... IDs):")
print(gene_check.columns[:10])

Gene File Columns (should be SIDM... IDs):
Index(['model_id', 'Unnamed: 1', 'Unnamed: 2', 'SIDM00001', 'SIDM00002',
       'SIDM00003', 'SIDM00005', 'SIDM00006', 'SIDM00007', 'SIDM00008'],
      dtype='object')

In [10]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv("C:/Users/abrup/Desktop/OncoMatch-Drug-Prediction/data/processed/AI_ready_matrix.csv")

In [12]:
df

,SANGER_MODEL_ID,DRUG_ID,LN_IC50,DRUG_NAME,SMILES,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
0,SIDM00872,1003,0.317741,Camptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,4.0152,1.7442,0.0426,0.2869,0.1375,...,1.3951,2.6112,3.6915,1.7181,0.0,3.1795,7.9192,NaN,3.7655,4.4289
1,SIDM00866,1003,0.636184,Camptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,2.4114,2.8197,0.2388,0.0144,0.1890,...,0.7398,1.8953,4.9500,1.9373,0.0,2.7949,6.3100,NaN,4.0321,4.4725
2,SIDM00885,1003,1.235544,Camptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,1.3618,1.7991,0.0566,0.1110,0.3219,...,1.8278,3.0875,3.4725,0.7570,0.0,4.2578,5.4538,0.0,3.8787,5.2145
3,SIDM00884,1003,-2.255899,Camptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,3.1554,2.0426,0.0144,3.8540,0.0144,...,0.9635,1.8718,2.8440,2.3391,0.0,2.1010,7.7668,NaN,4.0461,3.8836
4,SIDM00877,1003,-3.247021,Camptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...,2.0179,1.6645,0.0566,0.0841,0.1890,...,0.2869,1.0704,4.8410,2.9146,0.0,2.5385,5.0734,NaN,2.8817,4.5040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,SIDM00954,1013,2.407980,Nilotinib,CC1=C(C=C(C=C1)C(=O)NC2=CC(=CC(=C2)C(F)(F)F)N3...,4.0054,2.9946,0.0426,5.9923,1.0215,...,1.7268,2.7592,4.1643,3.7409,0.0,4.0807,7.4558,0.0,3.6859,6.7866
466,SIDM00940,1013,3.188158,Nilotinib,CC1=C(C=C(C=C1)C(=O)NC2=CC(=CC(=C2)C(F)(F)F)N3...,6.4515,3.8530,0.0000,0.2869,0.4854,...,1.1570,2.2957,3.0321,2.9635,0.0,2.9910,6.2388,NaN,3.1326,5.0130
467,SIDM01001,1013,0.348671,Nilotinib,CC1=C(C=C(C=C1)C(=O)NC2=CC(=CC(=C2)C(F)(F)F)N3...,0.2750,0.6041,0.1375,0.8797,0.8718,...,0.0000,1.9298,4.3198,0.3785,0.0,2.6182,4.8268,NaN,3.1906,3.8227
468,SIDM01056,1013,3.144710,Nilotinib,CC1=C(C=C(C=C1)C(=O)NC2=CC(=CC(=C2)C(F)(F)F)N3...,3.9946,2.2510,0.0000,0.0566,0.3448,...,1.2079,2.2660,4.4496,2.5945,0.0,2.6135,3.9107,NaN,3.7312,3.8570
469,SIDM01042,1013,0.411258,Nilotinib,CC1=C(C=C(C=C1)C(=O)NC2=CC(=CC(=C2)C(F)(F)F)N3...,3.6927,3.2388,0.0144,0.0286,0.2016,...,1.5993,2.7485,4.7634,2.0670,0.0,3.8248,5.1127,0.0,3.7677,4.8248

In [13]:
print("-" * 30)
print(f"Matrix Shape: {df.shape}")
print(f"Number of Drugs: {df['DRUG_NAME'].nunique()}")
print(f"Number of Cell Lines: {df['SANGER_MODEL_ID'].nunique()}")
print(f"Number of Genes: {len(df.columns) - 5}")

------------------------------
Matrix Shape: (470, 41150)
Number of Drugs: 10
Number of Cell Lines: 51
Number of Genes: 41145

In [14]:
nan_count = df.isna().sum().sum()
print("-" * 30)
print(f"Total Missing Values: {nan_count}")
if nan_count > 0:
    print("⚠️ Warning: You have missing values. You might need to impute them.")

------------------------------
Total Missing Values: 1763683
⚠️ Warning: You have missing values. You might need to impute them.

In [15]:
print("-" * 30)
print("Target Variable (LN_IC50) Stats:")
print(df['LN_IC50'].describe())

------------------------------
Target Variable (LN_IC50) Stats:
count    470.000000
mean       0.406118
std        3.383017
min       -6.975105
25%       -2.561561
50%        1.277375
75%        3.144435
max        7.353137
Name: LN_IC50, dtype: float64

In [16]:
random_gene = df.columns[100] 
print("-" * 30)
print(f"Example Gene ({random_gene}) Distribution:")
print(f"Min: {df[random_gene].min():.2f} | Max: {df[random_gene].max():.2f} | Mean: {df[random_gene].mean():.2f}")

------------------------------
Example Gene (ABCF1) Distribution:
Min: 5.03 | Max: 7.12 | Mean: 6.00

In [17]:
if df['SMILES'].iloc[0] is None:
    print("❌ ERROR: SMILES strings are missing!")
else:
    print("✅ SMILES strings are present.")

✅ SMILES strings are present.

In [30]:
cols_list = df.columns[df.isna().any()].tolist()

In [31]:
cols_list

['ABCF2P2',
 'ACTL10',
 'ADI1P3',
 'AGPAT5P1',
 'AP1B1P2',
 'ARMC2-AS1',
 'ATP5MFP3',
 'ATP6V0E1P4',
 'BPY2DP',
 'BRCA1P1',
 'C3orf36',
 'C3orf49P1',
 'C8orf44',
 'C8orf44-SGK3',
 'CALCP',
 'CASP1P1',
 'CDH23-AS1',
 'CDR1',
 'CDY17P',
 'CDY19P',
 'CDY8P',
 'CFTRP2',
 'CHEK2P4',
 'CHMP4AP1',
 'CLUHP1',
 'CLUHP11',
 'COX5BP8',
 'COX6CP11',
 'COX6CP8',
 'CST2P1',
 'CST9LP2',
 'CT47A10',
 'CT47A11',
 'CT47A12',
 'CT47A2',
 'CT47A3',
 'CT47A4',
 'CT47A5',
 'CT47A8',
 'CT47A9',
 'CYCSP44',
 'CYCSP53',
 'CYP2C60P',
 'CYP3A137P',
 'CYP3A52P',
 'CYP3A54P',
 'CYP4A27P',
 'CYP4A43P',
 'CYP4A44P',
 'DDIT4-AS1',
 'DDX3P2',
 'DEFB106A',
 'DEFB108C',
 'DEFB113',
 'DEFB130D',
 'DEFB131D',
 'DMD-AS3',
 'DUS4L-BCAP29',
 'DUX4L1',
 'DUX4L10',
 'DUX4L11',
 'DUX4L14',
 'DUX4L15',
 'DUX4L2',
 'DUX4L20',
 'DUX4L21',
 'DUX4L22',
 'DUX4L23',
 'DUX4L24',
 'DUX4L29',
 'DUX4L3',
 'DUX4L5',
 'DUX4L6',
 'DUX4L7',
 'DYNAPP1',
 'DYNAPP3',
 'DYNLL1P5',
 'EIF1P2',
 'ELOA3BP',
 'ELOA3DP',
 'ELOA3P',
 'ELOCP30',
 'ELOCP35',
 'ETFRF1P1',
 'F8A1',
 'F8A2',
 'FABP5P4',
 'FAM27E4',
 'FAM9CP1',
 'FCF1P4',
 'FXYD6P3',
 'GAPDHP17',
 'GGCTP3',
 'GLUD1P9',
 'GNG5P1',
 'GNG5P5',
 'GPM6BP3',
 'GPR143YP',
 'GTF2IP22',
 'H2BP8',
 'H3P41',
 'H3P46',
 'HLA-N',
 'HLA-S',
 'HLA-Z',
 'HMGB1P22',
 'HMGB1P32',
 'HMGB3P3',
 'HRURF',
 'HSFY6P',
 'IGHD1-1',
 'IGHD1-14',
 'IGHD1-20',
 'IGHD1-26',
 'IGHD1-7',
 'IGHD1OR15-1A',
 'IGHD1OR15-1B',
 'IGHD2-15',
 'IGHD2-2',
 'IGHD2-21',
 'IGHD2-8',
 'IGHD2OR15-2A',
 'IGHD2OR15-2B',
 'IGHD3-10',
 'IGHD3-16',
 'IGHD3-22',
 'IGHD3-3',
 'IGHD3-9',
 'IGHD3OR15-3A',
 'IGHD3OR15-3B',
 'IGHD4-11',
 'IGHD4-17',
 'IGHD4-23',
 'IGHD4-4',
 'IGHD4OR15-4A',
 'IGHD4OR15-4B',
 'IGHD5-12',
 'IGHD5-18',
 'IGHD5-24',
 'IGHD5-5',
 'IGHD5OR15-5A',
 'IGHD5OR15-5B',
 'IGHD6-13',
 'IGHD6-19',
 'IGHD6-25',
 'IGHD6-6',
 'IGHD7-27',
 'IGHJ1',
 'IGHJ1P',
 'IGHJ2',
 'IGHJ2P',
 'IGHJ3',
 'IGHJ3P',
 'IGHJ4',
 'IGHJ5',
 'IGHJ6',
 'IGHV1OR16-2',
 'IGHVII-40-1',
 'IGHVII-46-1',
 'IGHVII-67-1',
 'IGHVIII-22-2',
 'IGHVIII-5-1',
 'IGHVIII-67-2',
 'IGKJ1',
 'IGKJ2',
 'IGKJ3',
 'IGKJ4',
 'IGKJ5',
 'IGKV1D-32',
 'IGKV2-38',
 'IGKV2D-19',
 'IGKV3-34',
 'IGKV3D-34',
 'IGKV3OR2-5',
 'IGLJ4',
 'IGLJ5',
 'IGLJ6',
 'IGLJ7',
 'IGLVI-20',
 'IGLVVII-41-1',
 'KCNQ5-IT1',
 'KRT18P53',
 'KRTAP19-11P',
 'KRTAP20-3',
 'KRTAP23-1',
 'KRTAP5-14P',
 'KRTAP8-3P',
 'LARP7P2',
 'LINC00618',
 'LINC01075',
 'LINC01195',
 'LINC01628',
 'LINC01680',
 'LINC01737',
 'LINC01784',
 'LINC01949',
 'LINC02025',
 'LINC02276',
 'LINC02309',
 'LINC02479',
 'LINC02545',
 'LINC02578',
 'LINC02676',
 'LINC02905',
 'LNCDAT',
 'LSM1P2',
 'LUZP6',
 'MAFIP',
 'MED13P1',
 'MIR100',
 'MIR101-1',
 'MIR101-2',
 'MIR103A1',
 'MIR103A2',
 'MIR103B1',
 'MIR103B2',
 'MIR105-1',
 'MIR105-2',
 'MIR106A',
 'MIR106B',
 'MIR107',
 'MIR10A',
 'MIR10B',
 'MIR1-1',
 'MIR1178',
 'MIR1179',
 'MIR1180',
 'MIR1181',
 'MIR1182',
 'MIR1183',
 'MIR1184-1',
 'MIR1184-2',
 'MIR1184-3',
 'MIR1185-1',
 'MIR1185-2',
 'MIR1193',
 'MIR1197',
 'MIR1-2',
 'MIR1200',
 'MIR1202',
 'MIR1203',
 'MIR1204',
 'MIR1205',
 'MIR1206',
 'MIR1207',
 'MIR1208',
 'MIR122',
 'MIR1224',
 'MIR1225',
 'MIR1226',
 'MIR1227',
 'MIR1228',
 'MIR1229',
 'MIR1231',
 'MIR1233-1',
 'MIR1233-2',
 'MIR1234',
 'MIR1236',
 'MIR1237',
 'MIR1238',
 'MIR124-1',
 'MIR124-2',
 'MIR124-3',
 'MIR1243',
 'MIR1244-1',
 'MIR1244-2',
 'MIR1244-3',
 'MIR1244-4',
 'MIR1245A',
 'MIR1245B',
 'MIR1246',
 'MIR1248',
 'MIR1249',
 'MIR1250',
 'MIR1251',
 'MIR1252',
 'MIR1253',
 'MIR1255A',
 'MIR1255B1',
 'MIR1255B2',
 'MIR1256',
 'MIR1257',
 'MIR1258',
 'MIR125A',
 'MIR125B1',
 'MIR125B2',
 'MIR126',
 'MIR1260A',
 'MIR1260B',
 'MIR1261',
 'MIR1262',
 'MIR1263',
 'MIR1264',
 'MIR1265',
 'MIR1266',
 'MIR1267',
 'MIR1268A',
 'MIR1268B',
 'MIR1269A',
 'MIR1269B',
 'MIR127',
 'MIR1270',
 'MIR1271',
 'MIR1272',
 'MIR1273C',
 'MIR1273H',
 'MIR1275',
 'MIR1276',
 'MIR1277',
 'MIR1278',
 'MIR1279',
 'MIR128-1',
 'MIR1281',
 'MIR128-2',
 'MIR1282',
 'MIR1283-1',
 'MIR1283-2',
 'MIR1284',
 'MIR1285-1',
 'MIR1285-2',
 'MIR1286',
 'MIR1287',
 'MIR1288',
 'MIR1289-2',
 'MIR1290',
 'MIR129-1',
 'MIR1291',
 'MIR129-2',
 'MIR1292',
 'MIR1293',
 'MIR1295A',
 'MIR1295B',
 'MIR1296',
 'MIR1297',
 'MIR1298',
 'MIR1299',
 'MIR1301',
 'MIR1302-1',
 'MIR1302-4',
 'MIR1302-6',
 'MIR1302-7',
 'MIR1303',
 'MIR1304',
 'MIR1305',
 'MIR1306',
 'MIR130A',
 'MIR130B',
 'MIR132',
 'MIR1321',
 'MIR1322',
 'MIR1323',
 'MIR1324',
 'MIR133A1',
 'MIR133A2',
 'MIR134',
 'MIR1343',
 'MIR135A1',
 'MIR135A2',
 'MIR135B',
 'MIR136',
 'MIR137',
 'MIR138-1',
 'MIR138-2',
 'MIR139',
 'MIR140',
 'MIR141',
 'MIR142',
 'MIR143',
 'MIR144',
 'MIR145',
 'MIR1468',
 'MIR1469',
 'MIR146A',
 'MIR146B',
 'MIR1470',
 'MIR1471',
 'MIR147A',
 'MIR147B',
 'MIR148A',
 'MIR148B',
 'MIR149',
 'MIR150',
 'MIR151A',
 'MIR151B',
 'MIR152',
 'MIR153-1',
 'MIR153-2',
 'MIR1537',
 'MIR1538',
 'MIR1539',
 'MIR154',
 'MIR155',
 'MIR1587',
 'MIR15A',
 'MIR15B',
 'MIR16-1',
 'MIR16-2',
 'MIR17',
 'MIR181A1',
 'MIR181A2',
 'MIR181B1',
 'MIR181B2',
 'MIR181C',
 'MIR182',
 'MIR1825',
 'MIR1827',
 'MIR183',
 'MIR184',
 'MIR185',
 'MIR186',
 'MIR187',
 'MIR188',
 'MIR18A',
 'MIR18B',
 'MIR1908',
 'MIR1909',
 'MIR190A',
 'MIR190B',
 'MIR191',
 'MIR1910',
 'MIR1911',
 'MIR1912',
 'MIR1913',
 'MIR1914',
 'MIR1915',
 'MIR192',
 'MIR193A',
 'MIR193B',
 'MIR194-1',
 'MIR194-2',
 'MIR195',
 'MIR196A1',
 'MIR196A2',
 'MIR196B',
 'MIR197',
 'MIR1972-1',
 'MIR1972-2',
 'MIR1973',
 'MIR1976',
 'MIR198',
 'MIR199A1',
 'MIR199A2',
 'MIR199B',
 'MIR19A',
 'MIR19B1',
 'MIR19B2',
 'MIR200A',
 'MIR200B',
 'MIR200C',
 'MIR202',
 'MIR203A',
 'MIR203B',
 'MIR204',
 'MIR205',
 'MIR2052',
 'MIR2053',
 'MIR2054',
 'MIR206',
 'MIR208A',
 'MIR208B',
 'MIR20A',
 'MIR20B',
 'MIR21',
 'MIR210',
 'MIR211',
 'MIR2110',
 'MIR2113',
 'MIR2114',
 'MIR2115',
 'MIR2116',
 'MIR2117',
 'MIR212',
 'MIR215',
 'MIR216A',
 'MIR216B',
 'MIR217',
 'MIR218-1',
 'MIR218-2',
 'MIR219A1',
 'MIR219A2',
 'MIR219B',
 'MIR22',
 'MIR221',
 'MIR222',
 'MIR223',
 'MIR224',
 'MIR2276',
 'MIR2277',
 'MIR2278',
 'MIR2355',
 'MIR2392',
 'MIR23A',
 'MIR23B',
 'MIR23C',
 'MIR24-1',
 'MIR24-2',
 'MIR2467',
 'MIR25',
 'MIR2681',
 'MIR2682',
 'MIR26A1',
 'MIR26A2',
 'MIR26B',
 'MIR27A',
 'MIR27B',
 'MIR28',
 'MIR2861',
 'MIR2909',
 'MIR296',
 'MIR297',
 'MIR298',
 'MIR299',
 'MIR29A',
 'MIR29B1',
 'MIR29B2',
 'MIR29C',
 'MIR300',
 'MIR301A',
 'MIR301B',
 'MIR302A',
 'MIR302B',
 'MIR302C',
 'MIR302D',
 'MIR302E',
 'MIR302F',
 'MIR3064',
 'MIR3065',
 'MIR3074',
 'MIR30A',
 'MIR30B',
 'MIR30C1',
 'MIR30C2',
 'MIR30D',
 'MIR30E',
 'MIR31',
 'MIR3115',
 'MIR3116-1',
 'MIR3116-2',
 'MIR3117',
 'MIR3118-1',
 'MIR3118-2',
 'MIR3118-3',
 'MIR3118-4',
 'MIR3119-1',
 'MIR3119-2',
 'MIR3120',
 'MIR3121',
 'MIR3122',
 'MIR3123',
 'MIR3124',
 'MIR3125',
 'MIR3126',
 'MIR3127',
 'MIR3128',
 'MIR3129',
 'MIR3130-1',
 'MIR3130-2',
 'MIR3131',
 'MIR3132',
 'MIR3133',
 'MIR3134',
 'MIR3135A',
 'MIR3135B',
 'MIR3136',
 'MIR3137',
 'MIR3138',
 'MIR3139',
 'MIR3140',
 'MIR3141',
 'MIR3142',
 'MIR3143',
 'MIR3144',
 'MIR3145',
 'MIR3146',
 'MIR3147',
 'MIR3148',
 'MIR3149',
 'MIR3150A',
 'MIR3150B',
 'MIR3151',
 'MIR3152',
 'MIR3153',
 'MIR3154',
 'MIR3155A',
 'MIR3155B',
 'MIR3156-1',
 'MIR3156-2',
 'MIR3156-3',
 'MIR3157',
 'MIR3158-1',
 'MIR3158-2',
 'MIR3159',
 'MIR3160-1',
 'MIR3160-2',
 'MIR3161',
 'MIR3162',
 'MIR3163',
 'MIR3164',
 'MIR3165',
 'MIR3166',
 'MIR3167',
 'MIR3168',
 'MIR3169',
 'MIR3170',
 'MIR3171',
 'MIR3173',
 'MIR3174',
 'MIR3175',
 'MIR3176',
 'MIR3177',
 'MIR3178',
 'MIR3179-1',
 'MIR3179-2',
 'MIR3179-3',
 'MIR3179-4',
 'MIR3180-1',
 'MIR3180-2',
 'MIR3180-3',
 'MIR3181',
 'MIR3182',
 'MIR3183',
 'MIR3184',
 'MIR3185',
 'MIR3186',
 'MIR3187',
 'MIR3188',
 'MIR3189',
 'MIR3190',
 'MIR3191',
 'MIR3192',
 'MIR3193',
 'MIR3194',
 'MIR3195',
 'MIR3196',
 'MIR3197',
 'MIR3198-1',
 'MIR3198-2',
 'MIR3199-1',
 'MIR3199-2',
 'MIR32',
 'MIR3200',
 'MIR3201',
 'MIR3202-1',
 'MIR3202-2',
 'MIR320A',
 'MIR320B1',
 'MIR320C1',
 'MIR320C2',
 'MIR320D1',
 'MIR320D2',
 'MIR320E',
 'MIR323A',
 'MIR323B',
 'MIR324',
 'MIR325',
 'MIR326',
 'MIR328',
 'MIR329-1',
 'MIR329-2',
 'MIR330',
 'MIR331',
 'MIR335',
 'MIR337',
 'MIR338',
 'MIR339',
 'MIR33A',
 'MIR33B',
 'MIR340',
 'MIR342',
 'MIR345',
 'MIR346',
 'MIR34A',
 'MIR34B',
 'MIR34C',
 'MIR3529',
 'MIR3591',
 'MIR3605',
 'MIR3606',
 'MIR3609',
 'MIR361',
 'MIR3610',
 'MIR3611',
 'MIR3612',
 'MIR3613',
 'MIR3614',
 'MIR3615',
 'MIR3616',
 'MIR3617',
 'MIR3618',
 'MIR3619',
 'MIR362',
 'MIR3620',
 'MIR3621',
 'MIR3622A',
 'MIR3622B',
 'MIR363',
 'MIR3646',
 'MIR3649',
 'MIR3650',
 'MIR3651',
 'MIR3652',
 'MIR3654',
 'MIR3655',
 'MIR3657',
 'MIR3658',
 'MIR3659',
 'MIR365A',
 'MIR365B',
 'MIR3660',
 'MIR3661',
 'MIR3662',
 'MIR3663',
 'MIR3664',
 'MIR3665',
 'MIR3666',
 'MIR3667',
 'MIR3668',
 'MIR367',
 'MIR3670-1',
 'MIR3670-2',
 'MIR3670-3',
 'MIR3670-4',
 'MIR3671',
 'MIR3672',
 'MIR3674',
 'MIR3675',
 'MIR3677',
 'MIR3678',
 'MIR3679',
 'MIR3680-1',
 'MIR3680-2',
 'MIR3681',
 'MIR3682',
 'MIR3683',
 'MIR3684',
 'MIR3685',
 'MIR3686',
 'MIR3688-1',
 'MIR3688-2',
 'MIR3689A',
 'MIR3689C',
 'MIR3689D1',
 'MIR3689D2',
 'MIR3689E',
 'MIR3689F',
 'MIR369',
 'MIR3690',
 'MIR3691',
 'MIR3692',
 'MIR370',
 'MIR3713',
 'MIR3714',
 'MIR371A',
 'MIR371B',
 'MIR372',
 'MIR373',
 'MIR374A',
 'MIR374B',
 'MIR374C',
 'MIR375',
 'MIR376A1',
 'MIR376A2',
 'MIR376B',
 'MIR376C',
 'MIR377',
 'MIR378A',
 'MIR378B',
 'MIR378C',
 'MIR378D1',
 'MIR378D2',
 'MIR378E',
 'MIR378F',
 'MIR378G',
 'MIR378H',
 'MIR378I',
 'MIR378J',
 'MIR379',
 'MIR380',
 'MIR381',
 'MIR382',
 'MIR383',
 'MIR384',
 'MIR3908',
 'MIR3910-1',
 'MIR3910-2',
 'MIR3911',
 'MIR3912',
 'MIR3913-1',
 'MIR3913-2',
 'MIR3914-1',
 'MIR3914-2',
 'MIR3915',
 'MIR3916',
 'MIR3917',
 'MIR3918',
 'MIR3919',
 'MIR3920',
 'MIR3921',
 'MIR3922',
 'MIR3923',
 'MIR3924',
 'MIR3925',
 'MIR3926-1',
 'MIR3926-2',
 'MIR3927',
 'MIR3928',
 'MIR3929',
 'MIR3934',
 'MIR3935',
 'MIR3936',
 'MIR3937',
 'MIR3938',
 'MIR3939',
 'MIR3940',
 'MIR3941',
 'MIR3942',
 'MIR3943',
 'MIR3944',
 'MIR3945',
 'MIR3960',
 'MIR3972',
 'MIR3973',
 'MIR3974',
 'MIR3975',
 'MIR3976',
 'MIR3977',
 'MIR3978',
 'MIR409',
 'MIR410',
 'MIR411',
 'MIR412',
 'MIR421',
 'MIR422A',
 'MIR423',
 'MIR424',
 'MIR425',
 'MIR4251',
 'MIR4252',
 'MIR4253',
 'MIR4254',
 'MIR4255',
 'MIR4256',
 'MIR4257',
 'MIR4258',
 'MIR4259',
 'MIR4260',
 'MIR4261',
 'MIR4262',
 'MIR4263',
 'MIR4264',
 'MIR4265',
 'MIR4266',
 'MIR4267',
 'MIR4268',
 'MIR4269',
 'MIR4270',
 'MIR4271',
 'MIR4272',
 'MIR4273',
 'MIR4274',
 'MIR4275',
 'MIR4276',
 'MIR4277',
 'MIR4278',
 'MIR4279',
 'MIR4280',
 'MIR4281',
 'MIR4282',
 'MIR4283-1',
 'MIR4283-2',
 'MIR4284',
 'MIR4285',
 'MIR4286',
 'MIR4287',
 'MIR4288',
 'MIR4289',
 'MIR429',
 'MIR4290',
 'MIR4291',
 'MIR4292',
 'MIR4293',
 'MIR4294',
 'MIR4295',
 'MIR4296',
 'MIR4297',
 'MIR4298',
 'MIR4299',
 'MIR4300',
 'MIR4301',
 'MIR4302',
 'MIR4303',
 'MIR4304',
 'MIR4305',
 'MIR4306',
 'MIR4307',
 'MIR4308',
 'MIR4309',
 'MIR431',
 'MIR4310',
 'MIR4311',
 'MIR4312',
 'MIR4313',
 'MIR4314',
 'MIR4315-1',
 'MIR4315-2',
 'MIR4316',
 'MIR4317',
 'MIR4318',
 'MIR4319',
 'MIR432',
 'MIR4320',
 'MIR4321',
 'MIR4322',
 'MIR4323',
 'MIR4324',
 'MIR4325',
 'MIR4326',
 'MIR4327',
 'MIR4328',
 'MIR4329',
 'MIR433',
 'MIR4330',
 'MIR4418',
 'MIR4420',
 'MIR4421',
 'MIR4422',
 'MIR4423',
 'MIR4424',
 'MIR4425',
 'MIR4426',
 'MIR4427',
 'MIR4428',
 'MIR4429',
 'MIR4430',
 'MIR4431',
 'MIR4432',
 'MIR4433A',
 'MIR4433B',
 'MIR4434',
 'MIR4435-1',
 'MIR4435-2',
 'MIR4436A',
 'MIR4436B1',
 'MIR4436B2',
 'MIR4437',
 'MIR4438',
 'MIR4439',
 'MIR4440',
 'MIR4441',
 'MIR4442',
 'MIR4443',
 'MIR4444-1',
 'MIR4444-2',
 'MIR4445',
 'MIR4446',
 'MIR4447',
 'MIR4448',
 'MIR4449',
 'MIR4450',
 'MIR4451',
 'MIR4452',
 'MIR4453',
 'MIR4454',
 'MIR4455',
 'MIR4456',
 'MIR4457',
 'MIR4458',
 'MIR4460',
 'MIR4462',
 'MIR4463',
 'MIR4464',
 'MIR4465',
 'MIR4466',
 'MIR4467',
 'MIR4468',
 'MIR4469',
 'MIR4470',
 'MIR4471',
 'MIR4472-1',
 'MIR4472-2',
 'MIR4473',
 'MIR4474',
 'MIR4475',
 'MIR4476',
 'MIR4477A',
 'MIR4477B',
 'MIR4478',
 'MIR4479',
 'MIR448',
 'MIR4480',
 'MIR4481',
 'MIR4482',
 'MIR4483',
 'MIR4484',
 'MIR4485',
 'MIR4486',
 'MIR4487',
 'MIR4488',
 'MIR4489',
 'MIR4490',
 ...]

In [32]:
gene_cols = [c for c in df.columns if c not in ['SANGER_MODEL_ID', 'DRUG_NAME', 'SMILES', 'LN_IC50']]
variances = df[gene_cols].var().sort_values(ascending=False)

print("Top 10 Most Variable (Important) Genes:")
print(variances.head(10))

print("\nBottom 10 Least Variable (Useless) Genes:")
print(variances.tail(10))

Top 10 Most Variable (Important) Genes:
TFF1       20.917678
SCGB2A2    18.753956
KRT81      15.750022
GSTP1      15.357007
AGR2       15.217763
TFF3       14.999990
SPARC      14.107760
IGFBP5     14.010166
S100A9     13.812325
AKR1B1     13.626986
dtype: float64

Bottom 10 Least Variable (Useless) Genes:
RPL12P49   NaN
RPL41P5    NaN
SNORA30B   NaN
SNORD12B   NaN
SNORD23    NaN
SNORD67    NaN
SNORD8     NaN
SNORD87    NaN
SNORD89    NaN
SNORD9     NaN
dtype: float64